BASE_URL = "https://www.saucedemo.com"
TEST_INPUTS_XLSX = "data/test_inputs.xlsx"
USERNAME_ID = "user-name"
PASSWORD_ID = "password"
LOGIN_BUTTON_ID ="login-button"
ERROR_MESSAGE_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
USERNAME_PASSWORD_DONT_MATCH = "Epic sadface: Username and password do not match any user in this service"
MENUBUTTON_ID = "react-burger-menu-btn"
LOGOUT_XPATH = "//*[@id='logout_sidebar_link']"
CART_SIZE_XPATH = "//*[@id='shopping_cart_container']/a/span"
ERROR_USER = "error_user"
STANDARD_USER ="standard_user"
PASSWORD = "secret_sauce"

